[workspace]
members = [
    "crates/mmlx-macros",
    "crates/mmlx-core",
    "crates/mmlx-synth",
    "crates/mmlx-audio",
    "crates/mmlx-repl",
    "crates/mmlx-server",
    "crates/mmlx-algo",
    "crates/mmlx-fx",
    "crates/mmlx-midi",
    "crates/mmlx-songs",
]
resolver = "2"

[workspace.dependencies]
mmlx-core = { path = "crates/mmlx-core" }
mmlx-macros = { path = "crates/mmlx-macros" }
mmlx-synth = { path = "crates/mmlx-synth" }
mmlx-audio = { path = "crates/mmlx-audio" }
