// mmlx-core/src/lib.rs

// Core data structures (Note, ParamValue, Envelope, …) plus the composition
// operators, independent of any audio synthesis engine. Ported from CP437
// `castle_audio_core`.

pub mod types;
#[macro_use]
pub mod macros;
pub mod note;

/// Compatibility module for macros generated by mmlx-macros.
/// Generated note macros address `$crate::play::note::*`, so keep this alias.
pub mod play {
    /// Re-export the `note` module so `play::note::c4h`, etc. resolve correctly
    pub use crate::note;
    /// Alias the core `Note` type for patterns like `play::Note::ParamSetter`
    pub use crate::Note;
}

// Re-export the core types and helpers defined in types.rs
pub use types::{generate_unique_note_id, Instrument, MusicalEventType, TimedMusicalEvent};
pub use types::{
    get_base_midi_and_offset, get_duration_symbol, get_key_signature_adjustment,
    parse_key_signature, transpose_note,
};
pub use types::{Duration, Envelope, EnvelopePoint, InterpolationType, Note, ParamValue, TimeUnit};

// Re-export functions from macros module
pub use macros::create_param_setter;
pub use macros::resolve_key_value;

// Composition-body frontend: `ser!(c4q d4q)` ≡ `ser!([c4q, d4q])`.
// The proc macro only splits items; runtime `ser()`/`par()`/… resolve.
pub use mmlx_macros::seq_items;

// Re-export note module functions
pub use types::{forkpar, forkseq, note_stream_to_event_stream, par, parmin, ser};
pub use types::{NoteIterator, ReplContext, TimedMusicalEventIterator};

// --- Prelude for easy import ---
pub mod prelude {
    // Re-export types defined in this crate
    pub use super::{generate_unique_note_id, Instrument, MusicalEventType, TimedMusicalEvent};
    pub use super::{
        Duration, Envelope, EnvelopePoint, InterpolationType, Note, ParamValue, TimeUnit,
    };
    // Composition DSL macros: CP437 spellings + mmlx canonical aliases.
    // NOTE: `ser!`/`par!`/`parmin!`/`forkseq!`/`forkser!`/`forkpar!` wrapper
    // macros share names with the `ser()`/`par()`/… functions, so they are
    // NOT re-exported here (the names would collide). They are available via
    // `#[macro_use] extern crate mmlx_core;` or full path (`mmlx_core::ser!`).
    // All other macros are safe to glob-import.
    pub use crate::{comment, repeat};
    pub use crate::{
        cosen, cosenv, cuben, cubenv, en, env, expen, expenv, linen, linenv, param, param_opt,
    };

    // Re-export helpers
    pub use super::{
        get_base_midi_and_offset, get_duration_symbol, get_key_signature_adjustment,
        parse_key_signature, transpose_note,
    };

    // Re-export note functions
    pub use super::{forkpar, forkseq, note_stream_to_event_stream, par, parmin, ser};
    pub use super::{NoteIterator, TimedMusicalEventIterator};

    // Re-export all predefined notes
    pub use crate::note::*;

    // Make macro helper functions available in prelude
    pub use super::{create_param_setter, resolve_key_value};
}
