[package]
name = "mmlx-repl"
version = "0.1.0"
edition = "2021"

[features]
default = []
audio = ["mmlx-audio/audio", "dep:cpal"]

[dependencies]
mmlx-core = { workspace = true }
mmlx-audio = { workspace = true }
evcxr = "0.20"
anyhow = "1.0"
serde_json = "1.0"
rand = "0.9"
log = "0.4"
env_logger = "0.11"
rustyline = "16.0"
syntect = "5.2"
crossbeam-channel = "0.5"
cpal = { version = "0.15.3", optional = true }

[[bin]]
name = "mmlx-repl"
path = "src/main.rs"
