[package]
name = "mmlx-server"
version = "0.1.0"
edition = "2021"

[features]
default = []
audio = ["mmlx-audio/audio"]

[dependencies]
mmlx-core = { workspace = true }
mmlx-algo = { workspace = true }
mmlx-audio = { workspace = true }
mmlx-repl = { path = "../mmlx-repl" }
mmlx-songs = { path = "../mmlx-songs" }
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
mmlx-ym = { workspace = true }
mmlx-chip = { workspace = true }

[[bin]]
name = "mmlx-server"
path = "src/main.rs"
